# Generated by Django 5.0 on 2024-01-03 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenitie', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('Ame_description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='branch_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_image', models.ImageField(upload_to='')),
                ('room_numbers', models.CharField(max_length=200)),
                ('contact_by_mobile', models.CharField(max_length=11)),
                ('contact_by_mail', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('Branchlocation', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recepie_name', models.CharField(max_length=31)),
                ('Recepie_image', models.ImageField(upload_to='')),
                ('meal_type', models.CharField(max_length=50, null=True)),
                ('Food_category', models.CharField(max_length=50)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Recepie_Category', models.CharField(max_length=50, null=True)),
                ('recepie_description', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('hotel_type', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('amenities', models.CharField(max_length=500)),
                ('policy', models.BooleanField()),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_name', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('Hotel_registration_number', models.CharField(max_length=14)),
                ('hotel_image', models.ImageField(upload_to='')),
                ('contact_by_mobile', models.CharField(max_length=200)),
                ('contact_by_mail', models.CharField(max_length=200)),
                ('About_us', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manageusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('id_proof', models.ImageField(upload_to='')),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='cctv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cctv', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.branch_management')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.department')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_joining', models.DateField()),
                ('employee_age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('emp_address', models.CharField(max_length=500)),
                ('nationality', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=200)),
                ('alternative_mobile_number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('shift_timings', models.CharField(max_length=200)),
                ('type_of_emp', models.CharField(max_length=200)),
                ('passport_image', models.ImageField(upload_to='')),
                ('id_prooof', models.ImageField(upload_to='')),
                ('certificates', models.ImageField(upload_to='')),
                ('signature', models.ImageField(upload_to='')),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.branch_management')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.designation')),
            ],
        ),
        migrations.CreateModel(
            name='fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_drills', models.IntegerField(default=0)),
                ('desc_d', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.branch_management')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=True, null=True)),
                ('number_of_guest', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_child', models.IntegerField(blank=True, default=0, null=True)),
                ('check_in', models.CharField(max_length=200)),
                ('check_out', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.branch_management')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.room')),
            ],
        ),
        migrations.CreateModel(
            name='Adding_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_image', models.ImageField(upload_to='')),
                ('Room_number', models.CharField(max_length=200)),
                ('Room_area', models.IntegerField()),
                ('No_of_beds', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Room_description', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.branch_management')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapk.room')),
            ],
        ),
    ]
