# Generated by Django 5.0 on 2024-01-03 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('registration_count', models.PositiveIntegerField(default=0, editable=False)),
                ('user_full_name', models.CharField(max_length=250)),
                ('user_image', models.ImageField(upload_to='users')),
                ('user_name', models.CharField(max_length=80, unique=True)),
                ('user_gender', models.CharField(max_length=80)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_nationality', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_mobile_number', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=80)),
                ('user_otp', models.IntegerField(blank=True, null=True)),
                ('user_address', models.CharField(max_length=200)),
                ('user_adhaar_number', models.IntegerField(blank=True, null=True)),
                ('user_adhaar_pdf', models.FileField(upload_to='')),
                ('user_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-user_date'],
            },
        ),
    ]
